### ISSUE TITLE
Backslash in code comment

### ISSUE THREAD

**Issue by KronosTheLate** [simeonschaub/JuliaMono.jl#2]
Code comments are indented by default, at least to me in VSCode. This causes a problem with JuliaMono, which I think is fully described by the screenshot below:
![image](https://user-images.githubusercontent.com/61620837/97584943-de793000-19f8-11eb-9012-58461b7488f8.png)
I like julia mono (a lot. Thank you for it), but I find this behaviour to be sub-optimal :/

Another not really important thing - I think it was fun to have emojis in the font, which they were by default. Would that be hard to implement? I imagine that they can simply be copied, and if one can create a variable with the perfect emoji as name, it is just pure art. I have never done it, but I like the possibility of it happening ^_^

**Comment by simeonschaub** [comment]
I think you probably meant to open this issue at https://github.com/cormullion/juliamono. This repo is just an installer for that font, which I still need to finish, maybe I should add a README mentioning that. Did you actually use this to install the font? I haven't updated the version of the font in a while, I should probably do that, but before you open an issue on the actual repo, I would check against the latest version. If there is interest in an installer like this, I could try to look into how to update this for new JuliaMono versions automatically.

**Comment by KronosTheLate** [comment]
I have not used this installer, no. It just came up first when googling Julia Mono. Whoopsie

I will try to update and see if the issue persists, and open it at the appropriate location if it does ^_^
